import sqlite3
import joblib
import numpy as np
import pandas as pd
from pydantic import BaseModel, Field
from typing import Annotated
from fastapi import FastAPI, HTTPException


app = FastAPI(title = 'Industrial Predictive Maintainance API')
DB_PATH = 'data/telementry_storage.db'
MODEL_PATH = 'models/predictive_model.pkl'

try:
    model = joblib.load(MODEL_PATH)
except FileNotFoundError:
    raise RuntimeError(f'Critical Error: Model weight file not found at {MODEL_PATH}')

class SensorPayload(BaseModel):
    machine_id: Annotated[int, Field(..., description='Unique integer identifier for asset registry query', ge=1, le=10000)]
    air_temperature: Annotated[float, Field(..., description = 'air temperture in kelvin', gt=0)]
    process_temperature: Annotated[float, Field(...,description="Process operating temperature measured in Kelvin.",gt=0.0)]
    
    rotational_speed: Annotated[float, Field(...,description="Spindle rotational speed measured in RPM.",ge=0.0)]
    
    torque: Annotated[float, Field(...,description="Torque generated by the machine cutting assembly in Nm.",ge=0.0)]
    
    tool_wear: Annotated[float, Field(...,description="Accumulated execution time of the cutting tool in minutes.",ge=0.0, le=300.0)]

def get_machine_metadata(machine_id: int):
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('SELECT machine_type FROM machine_metadata WHERE machine_id= ?', (machine_id,))
    result = cursor.fetchone()
    conn.close()
    return result[0] if result else None

@app.post('/predict')
def predict_maintainance(payload: SensorPayload):
    machine_type = get_machine_metadata(payload.machine_id)
    if machine_type is None:
        raise HTTPException(status_code =404, detail= f'Asset ID{payload.machine_id} not found in telemetry registry')
    type_L = 1 if machine_type == 'L' else 0
    type_M = 1 if machine_type == 'M' else 0
    type_H = 1 if machine_type == 'H' else 0

    temp_delta = payload.process_temperature - payload.air_temperature
    power_watts = payload.torque * (payload.rotational_speed*(2*np.pi/60))
    overstrain_factor = payload.tool_wear * payload.torque

    feature_matrix = pd.DataFrame([{
        'air_temperature': payload.air_temperature,
        'process_temperature': payload.process_temperature,
        'rotational_speed': payload.rotational_speed,
        'torque': payload.torque,
        'tool_wear': payload.tool_wear,
        'machine_type_H': type_H,
        'machine_type_L': type_L,
        'machine_type_M': type_M,
        'temp_delta': temp_delta,
        'power_watts': power_watts,
        'overstrain_factor': overstrain_factor
    }])
    expected_features = model.feature_names_in_
    feature_matrix = feature_matrix[expected_features]

    prediction = int(model.predict(feature_matrix)[0])
    probability = float(model.predict_proba(feature_matrix)[0][1])

    return {'machine_id': payload.machine_id,
            'machine_type_resolved': machine_type,
            'failure_prediction': prediction,
            'failure_probability': round(probability, 4),
            'status_alert': 'Critical_danger_shutdown' if prediction ==1 else 'Operational_Normal'
    }